version: '3'
services:
  nodered:
    build:
      context: ./nodered/
      dockerfile: Dockerfile
    env_file:
      - .env-dev
    restart: always
    labels:
      - traefik.enable=false
    volumes:
      - node_red_data:/data
      - ./nodered/settings.js:/data/settings.js
    networks:
      - internal
    ports:
      - "1881:1880"
volumes:
  node_red_data:
networks:
  internal:
    external: false
